/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class openmovement_JOMAPI */

#ifndef _Included_openmovement_JOMAPI
#define _Included_openmovement_JOMAPI
#ifdef __cplusplus
extern "C" {
#endif
#undef openmovement_JOMAPI_OM_VERSION
#define openmovement_JOMAPI_OM_VERSION 103L
#undef openmovement_JOMAPI_OM_DEVICE_REMOVED
#define openmovement_JOMAPI_OM_DEVICE_REMOVED 0L
#undef openmovement_JOMAPI_OM_DEVICE_CONNECTED
#define openmovement_JOMAPI_OM_DEVICE_CONNECTED 1L
#undef openmovement_JOMAPI_OM_MEMORY_HEALTH_ERROR
#define openmovement_JOMAPI_OM_MEMORY_HEALTH_ERROR 1L
#undef openmovement_JOMAPI_OM_MEMORY_HEALTH_WARNING
#define openmovement_JOMAPI_OM_MEMORY_HEALTH_WARNING 8L
#undef openmovement_JOMAPI_OM_LED_UNKNOWN
#define openmovement_JOMAPI_OM_LED_UNKNOWN -2L
#undef openmovement_JOMAPI_OM_LED_AUTO
#define openmovement_JOMAPI_OM_LED_AUTO -1L
#undef openmovement_JOMAPI_OM_LED_OFF
#define openmovement_JOMAPI_OM_LED_OFF 0L
#undef openmovement_JOMAPI_OM_LED_BLUE
#define openmovement_JOMAPI_OM_LED_BLUE 1L
#undef openmovement_JOMAPI_OM_LED_GREEN
#define openmovement_JOMAPI_OM_LED_GREEN 2L
#undef openmovement_JOMAPI_OM_LED_CYAN
#define openmovement_JOMAPI_OM_LED_CYAN 3L
#undef openmovement_JOMAPI_OM_LED_RED
#define openmovement_JOMAPI_OM_LED_RED 4L
#undef openmovement_JOMAPI_OM_LED_MAGENTA
#define openmovement_JOMAPI_OM_LED_MAGENTA 5L
#undef openmovement_JOMAPI_OM_LED_YELLOW
#define openmovement_JOMAPI_OM_LED_YELLOW 6L
#undef openmovement_JOMAPI_OM_LED_WHITE
#define openmovement_JOMAPI_OM_LED_WHITE 7L
#undef openmovement_JOMAPI_OM_METADATA_SIZE
#define openmovement_JOMAPI_OM_METADATA_SIZE 448L
#undef openmovement_JOMAPI_OM_ERASE_NONE
#define openmovement_JOMAPI_OM_ERASE_NONE 0L
#undef openmovement_JOMAPI_OM_ERASE_DELETE
#define openmovement_JOMAPI_OM_ERASE_DELETE 1L
#undef openmovement_JOMAPI_OM_ERASE_QUICKFORMAT
#define openmovement_JOMAPI_OM_ERASE_QUICKFORMAT 2L
#undef openmovement_JOMAPI_OM_ERASE_WIPE
#define openmovement_JOMAPI_OM_ERASE_WIPE 3L
#undef openmovement_JOMAPI_OM_ACCEL_DEFAULT_RATE
#define openmovement_JOMAPI_OM_ACCEL_DEFAULT_RATE 100L
#undef openmovement_JOMAPI_OM_ACCEL_DEFAULT_RANGE
#define openmovement_JOMAPI_OM_ACCEL_DEFAULT_RANGE 8L
#undef openmovement_JOMAPI_OM_DOWNLOAD_NONE
#define openmovement_JOMAPI_OM_DOWNLOAD_NONE 0L
#undef openmovement_JOMAPI_OM_DOWNLOAD_ERROR
#define openmovement_JOMAPI_OM_DOWNLOAD_ERROR 1L
#undef openmovement_JOMAPI_OM_DOWNLOAD_PROGRESS
#define openmovement_JOMAPI_OM_DOWNLOAD_PROGRESS 2L
#undef openmovement_JOMAPI_OM_DOWNLOAD_COMPLETE
#define openmovement_JOMAPI_OM_DOWNLOAD_COMPLETE 3L
#undef openmovement_JOMAPI_OM_DOWNLOAD_CANCELLED
#define openmovement_JOMAPI_OM_DOWNLOAD_CANCELLED 4L
#undef openmovement_JOMAPI_OM_TRUE
#define openmovement_JOMAPI_OM_TRUE 1L
#undef openmovement_JOMAPI_OM_FALSE
#define openmovement_JOMAPI_OM_FALSE 0L
#undef openmovement_JOMAPI_OM_OK
#define openmovement_JOMAPI_OM_OK 0L
#undef openmovement_JOMAPI_OM_E_FAIL
#define openmovement_JOMAPI_OM_E_FAIL -1L
#undef openmovement_JOMAPI_OM_E_UNEXPECTED
#define openmovement_JOMAPI_OM_E_UNEXPECTED -2L
#undef openmovement_JOMAPI_OM_E_NOT_VALID_STATE
#define openmovement_JOMAPI_OM_E_NOT_VALID_STATE -3L
#undef openmovement_JOMAPI_OM_E_OUT_OF_MEMORY
#define openmovement_JOMAPI_OM_E_OUT_OF_MEMORY -4L
#undef openmovement_JOMAPI_OM_E_INVALID_ARG
#define openmovement_JOMAPI_OM_E_INVALID_ARG -5L
#undef openmovement_JOMAPI_OM_E_POINTER
#define openmovement_JOMAPI_OM_E_POINTER -6L
#undef openmovement_JOMAPI_OM_E_NOT_IMPLEMENTED
#define openmovement_JOMAPI_OM_E_NOT_IMPLEMENTED -7L
#undef openmovement_JOMAPI_OM_E_ABORT
#define openmovement_JOMAPI_OM_E_ABORT -8L
#undef openmovement_JOMAPI_OM_E_ACCESS_DENIED
#define openmovement_JOMAPI_OM_E_ACCESS_DENIED -9L
#undef openmovement_JOMAPI_OM_E_INVALID_DEVICE
#define openmovement_JOMAPI_OM_E_INVALID_DEVICE -10L
#undef openmovement_JOMAPI_OM_E_UNEXPECTED_RESPONSE
#define openmovement_JOMAPI_OM_E_UNEXPECTED_RESPONSE -11L
#undef openmovement_JOMAPI_OM_E_LOCKED
#define openmovement_JOMAPI_OM_E_LOCKED -12L
#undef openmovement_JOMAPI_OM_DATETIME_ZERO
#define openmovement_JOMAPI_OM_DATETIME_ZERO 0i64
#undef openmovement_JOMAPI_OM_DATETIME_INFINITE
#define openmovement_JOMAPI_OM_DATETIME_INFINITE -1i64
#undef openmovement_JOMAPI_OM_DATETIME_MIN_VALID
#define openmovement_JOMAPI_OM_DATETIME_MIN_VALID 4325376i64
#undef openmovement_JOMAPI_OM_DATETIME_MAX_VALID
#define openmovement_JOMAPI_OM_DATETIME_MAX_VALID 4282351355i64
#undef openmovement_JOMAPI_OM_MAX_SAMPLES
#define openmovement_JOMAPI_OM_MAX_SAMPLES 120L
#undef openmovement_JOMAPI_OM_MAX_HEADER_SIZE
#define openmovement_JOMAPI_OM_MAX_HEADER_SIZE 1024L
#undef openmovement_JOMAPI_OM_MAX_DATA_SIZE
#define openmovement_JOMAPI_OM_MAX_DATA_SIZE 512L
#undef openmovement_JOMAPI_OM_VALUE_DEVICEID
#define openmovement_JOMAPI_OM_VALUE_DEVICEID 3L
#undef openmovement_JOMAPI_OM_VALUE_SESSIONID
#define openmovement_JOMAPI_OM_VALUE_SESSIONID 4L
#undef openmovement_JOMAPI_OM_VALUE_SEQUENCEID
#define openmovement_JOMAPI_OM_VALUE_SEQUENCEID 5L
#undef openmovement_JOMAPI_OM_VALUE_LIGHT
#define openmovement_JOMAPI_OM_VALUE_LIGHT 7L
#undef openmovement_JOMAPI_OM_VALUE_TEMPERATURE
#define openmovement_JOMAPI_OM_VALUE_TEMPERATURE 8L
#undef openmovement_JOMAPI_OM_VALUE_EVENTS
#define openmovement_JOMAPI_OM_VALUE_EVENTS 9L
#undef openmovement_JOMAPI_OM_VALUE_BATTERY
#define openmovement_JOMAPI_OM_VALUE_BATTERY 10L
#undef openmovement_JOMAPI_OM_VALUE_SAMPLERATE
#define openmovement_JOMAPI_OM_VALUE_SAMPLERATE 11L
#undef openmovement_JOMAPI_OM_VALUE_TEMPERATURE_MC
#define openmovement_JOMAPI_OM_VALUE_TEMPERATURE_MC 108L
#undef openmovement_JOMAPI_OM_VALUE_BATTERY_MV
#define openmovement_JOMAPI_OM_VALUE_BATTERY_MV 110L
#undef openmovement_JOMAPI_OM_VALUE_BATTERY_PERCENT
#define openmovement_JOMAPI_OM_VALUE_BATTERY_PERCENT 210L
/*
 * Class:     openmovement_JOMAPI
 * Method:    OmStartup
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmStartup
  (JNIEnv *, jclass, jint);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmShutdown
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmShutdown
  (JNIEnv *, jclass);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmSetLogStream
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmSetLogStream
  (JNIEnv *, jclass, jint);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmGetDeviceIds
 * Signature: ([II)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmGetDeviceIds
  (JNIEnv *, jclass, jintArray, jint);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmGetVersion
 * Signature: (I[I[I)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmGetVersion
  (JNIEnv *, jclass, jint, jintArray, jintArray);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmGetBatteryLevel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmGetBatteryLevel
  (JNIEnv *, jclass, jint);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmSelfTest
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmSelfTest
  (JNIEnv *, jclass, jint);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmGetMemoryHealth
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmGetMemoryHealth
  (JNIEnv *, jclass, jint);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmGetBatteryHealth
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmGetBatteryHealth
  (JNIEnv *, jclass, jint);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmGetAccelerometer
 * Signature: (I[I[I[I)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmGetAccelerometer
  (JNIEnv *, jclass, jint, jintArray, jintArray, jintArray);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmGetTime
 * Signature: (I[J)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmGetTime
  (JNIEnv *, jclass, jint, jlongArray);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmSetTime
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmSetTime
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmSetLed
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmSetLed
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmIsLocked
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmIsLocked
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmSetLock
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmSetLock
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmUnlock
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmUnlock
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmSetEcc
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmSetEcc
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmGetEcc
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmGetEcc
  (JNIEnv *, jclass, jint);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmGetDelays
 * Signature: (I[J[J)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmGetDelays
  (JNIEnv *, jclass, jint, jlongArray, jlongArray);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmSetDelays
 * Signature: (IJJ)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmSetDelays
  (JNIEnv *, jclass, jint, jlong, jlong);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmGetSessionId
 * Signature: (I[J)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmGetSessionId
  (JNIEnv *, jclass, jint, jlongArray);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmSetSessionId
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmSetSessionId
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmGetMetadata
 * Signature: (ILjava/lang/StringBuffer;)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmGetMetadata
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmSetMetadata
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmSetMetadata
  (JNIEnv *, jclass, jint, jstring, jint);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmGetLastConfigTime
 * Signature: (I[J)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmGetLastConfigTime
  (JNIEnv *, jclass, jint, jlongArray);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmEraseDataAndCommit
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmEraseDataAndCommit
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmGetAccelConfig
 * Signature: (I[I[I)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmGetAccelConfig
  (JNIEnv *, jclass, jint, jintArray, jintArray);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmSetAccelConfig
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmSetAccelConfig
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmGetDataFilename
 * Signature: (ILjava/lang/StringBuffer;)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmGetDataFilename
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmGetDataRange
 * Signature: (I[I[I[I[J[J)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmGetDataRange
  (JNIEnv *, jclass, jint, jintArray, jintArray, jintArray, jlongArray, jlongArray);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmBeginDownloading
 * Signature: (IIILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmBeginDownloading
  (JNIEnv *, jclass, jint, jint, jint, jstring);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmQueryDownload
 * Signature: (I[I[I)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmQueryDownload
  (JNIEnv *, jclass, jint, jintArray, jintArray);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmWaitForDownload
 * Signature: (I[I[I)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmWaitForDownload
  (JNIEnv *, jclass, jint, jintArray, jintArray);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmCancelDownload
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmCancelDownload
  (JNIEnv *, jclass, jint);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmErrorString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_openmovement_JOMAPI_OmErrorString
  (JNIEnv *, jclass, jint);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmReaderOpen
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_openmovement_JOMAPI_OmReaderOpen
  (JNIEnv *, jclass, jstring);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmReaderDataRange
 * Signature: (J[I[I[I[J[J)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmReaderDataRange
  (JNIEnv *, jclass, jlong, jintArray, jintArray, jintArray, jlongArray, jlongArray);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmReaderMetadata
 * Signature: (J[I[J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_openmovement_JOMAPI_OmReaderMetadata
  (JNIEnv *, jclass, jlong, jintArray, jlongArray);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmReaderDataBlockPosition
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmReaderDataBlockPosition
  (JNIEnv *, jclass, jlong);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmReaderDataBlockSeek
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmReaderDataBlockSeek
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmReaderNextBlock
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmReaderNextBlock
  (JNIEnv *, jclass, jlong);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmReaderBufferCopy
 * Signature: (J[S)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmReaderBufferCopy
  (JNIEnv *, jclass, jlong, jshortArray);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmReaderTimestamp
 * Signature: (JI[I)J
 */
JNIEXPORT jlong JNICALL Java_openmovement_JOMAPI_OmReaderTimestamp
  (JNIEnv *, jclass, jlong, jint, jintArray);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmReaderGetValue
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmReaderGetValue
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmReaderRawHeaderPacketCopy
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmReaderRawHeaderPacketCopy
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmReaderRawDataPacketCopy
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_openmovement_JOMAPI_OmReaderRawDataPacketCopy
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     openmovement_JOMAPI
 * Method:    OmReaderClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_openmovement_JOMAPI_OmReaderClose
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
