/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JOMAPI */

#ifndef _Included_JOMAPI
#define _Included_JOMAPI
#ifdef __cplusplus
extern "C" {
#endif
#undef JOMAPI_OM_VERSION
#define JOMAPI_OM_VERSION 103L
#undef JOMAPI_OM_DEVICE_REMOVED
#define JOMAPI_OM_DEVICE_REMOVED 0L
#undef JOMAPI_OM_DEVICE_CONNECTED
#define JOMAPI_OM_DEVICE_CONNECTED 1L
/*
 * Class:     JOMAPI
 * Method:    OmStartup
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_JOMAPI_OmStartup
  (JNIEnv *, jclass, jint);

/*
 * Class:     JOMAPI
 * Method:    OmShutdown
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_JOMAPI_OmShutdown
  (JNIEnv *, jclass);

/*
 * Class:     JOMAPI
 * Method:    OmSetLogStream
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_JOMAPI_OmSetLogStream
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
